#if defined farmer_included
	#endinput
#endif

#define farmer_included

#include <a_samp>
#include <ColAndreas>
#include <FCNPC>
#include <Pawn.CMD>

#include <util>
#include <subtitle>

#include "./farmer_employee.inc"

#include "./breed/breed_stats.inc"
#include "./breed/breed_area.inc"
#include "./breed/species/brown_cow.inc"
#include "./breed/species/diary_cow.inc"
#include "./breed/breed_lifecycle.inc"
#include "./breed/breed_cmds.inc"
#include "./breed/breed_key.inc"
#include "./breed/breed_actor.inc"
#include "./breed/breed_follow.inc"
#include "./breed/breed_spawn.inc"
#include "./breed/breed_nametag.inc"
#include "./breed/breed_trunk.inc"