#if defined app_call_included
	#endinput
#endif

#define app_call_included

// #include ".\item\ability\phone\app\call\call_contact.inc"
// #include ".\item\ability\phone\app\call\call_dial.inc"
// #include ".\item\ability\phone\app\call\call_incoming.inc"
// #include ".\item\ability\phone\app\call\call_perform.inc"
// #include ".\item\ability\phone\app\call\call_button.inc"
// #include ".\item\ability\phone\app\call\call_incoming_ui.inc"
// #include ".\item\ability\phone\app\call\call_dial_ui.inc"
// #include ".\item\ability\phone\app\call\call_perform_ui.inc"
// #include ".\item\ability\phone\app\call\call_contact_ui.inc"

#include ".\item\ability\phone\app\call\call_forwards.inc"

#include ".\item\ability\phone\app\call\call_contact.inc"
#include ".\item\ability\phone\app\call\call_contact_wrapper.inc"
#include ".\item\ability\phone\app\call\call_contact_ui.inc"
#include ".\item\ability\phone\app\call\call_dial.inc"
#include ".\item\ability\phone\app\call\call_dial_ui.inc"
#include ".\item\ability\phone\app\call\call_incoming.inc"
#include ".\item\ability\phone\app\call\call_incoming_ui.inc"
#include ".\item\ability\phone\app\call\call_session.inc"
#include ".\item\ability\phone\app\call\call_session_settings.inc"
#include ".\item\ability\phone\app\call\call_session_ui.inc"
#include ".\item\ability\phone\app\call\call_session_chat.inc"
#include ".\item\ability\phone\app\call\call_session_tests.inc"
#include ".\item\ability\phone\app\call\call_button.inc"