#if defined phone_app_included
	#endinput
#endif

#define phone_app_included

#include ".\ability\phone\app\app_stats.inc"

#include ".\ability\phone\app\menu\menu.inc"
#include ".\ability\phone\app\store\store.inc"
#include ".\ability\phone\app\call\call.inc"
#include ".\ability\phone\app\message\message.inc"
// #include ".\ability\phone\app\sungo_partner\sungo_partner.inc"
#include ".\ability\phone\app\sungo\sungo.inc"