#if defined item_included
	#endinput
#endif

#define item_included

#include <a_samp>
#include <a_mysql>
#include <YSI_Coding\y_inline>
#include <PawnPlus>
#include <Pawn.CMD>
#include <sscanf2>
#include <YSI_Extra\y_inline_mysql>
#include <pp-mysql>

#include <config/colors>

#include <mysql>

#include "./item_stats.inc"
#include "./item_ability_gun.inc"
#include "./item_ability_melee.inc"
#include "./item_admin_cmds.inc"